# resource_group_name = "Kenny-RG"
# location = "West US"
# flexibleServers_mysql_dev_name          = "testsqlflexible"
# virtualNetworks_resourceid              = "/subscriptions/50c2252e-5826-4532-a280-06590313ce7a/resourceGroups/Kenny-RG/providers/Microsoft.Network/virtualNetworks/Kenny-vnet"
# privateDnsZones_resourceid              = "/subscriptions/50c2252e-5826-4532-a280-06590313ce7a/resourceGroups/kenny-rg/providers/Microsoft.Network/privateDnsZones/kennydnszone.mysql.database.azure.com"
# userAssignedIdentities_mysql_resourceid = "/subscriptions/50c2252e-5826-4532-a280-06590313ce7a/resourceGroups/Kenny-RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kennyuserassigned"
# userAssignedIdentity_name = "kennyuserassigned"

resource_group_name = "DevOps-Learn"
location = "West Europe"
flexibleServers_mysql_dev_name          = "testsqlflexible"
virtualNetworks_resourceid              = "/subscriptions/4d2f3d90-3f7a-4f44-bb7f-bee999a3638b/resourceGroups/DevOps-Learn/providers/Microsoft.Network/virtualNetworks/DevOps"
privateDnsZones_resourceid              = "/subscriptions/4d2f3d90-3f7a-4f44-bb7f-bee999a3638b/resourceGroups/devops-learn/providers/Microsoft.Network/privateDnsZones/mayordnszone.mysql.database.azure.com"
userAssignedIdentities_mysql_resourceid = "/subscriptions/4d2f3d90-3f7a-4f44-bb7f-bee999a3638b/resourceGroups/DevOps-Learn/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mayorassigned"
userAssignedIdentity_name = "mayorassigned"
